### ISSUE TITLE
Se puede entrenar el modelo con preguntas del cliente y la respuesta de un funcionario de soporte?

### ISSUE THREAD

**Issue by Binapps** [OpenPipe/openpipe#220]
Lo digo en el sentido de capturar la pregunta y la respuesta del funcionario de soporte al cliente, en una plataforma de chat, cliente - funcionario, como tawkto por ejemplo. Dónde usando el API, se pueden descargar todos los chats en tiempo real, y hacer como que la respuesta del funcionario sea el prompt

**Comment by arcticfly** [comment]
Hey Binapps. Yes, training a small model on interactions between support staff and customers is possible, but may not always be advisable. If the staff have a wide range of possible answers and need to deal with many unrelated requests, then a small model will have trouble internalizing all the lessons it needs to learn from a large model in order to properly handle incoming requests. However, if the tasks you want your fine-tuned model to do are narrowly scoped, e.g. fulfill account update requests, triage incoming emails, etc, then a fine-tuned model could do just fine. Does that answer your question?

**Comment by Binapps** [comment]
Yes, thanks you!
