### ISSUE TITLE
[Discussion]  Auth optional when running locally

### ISSUE THREAD

**Issue by DVGY** [OpenPipe/openpipe#247]
I want to try create a PR for this. I have following question in my mind and I would like to discuss before implementing

1. Is it okay to add Email Provider and can be used by guest users locally ?

**Comment by arcticfly** [comment]
Hey @DVGY, thanks for putting thought into this, and asking for feedback!

I'm a little reluctant to add additional logic to our authentication flow right now. In order to ensure continued security and ease of access we'll need to think pretty hard about the optimal solution, and at the moment, our primary focus is optimizing the fine-tuning and model-serving flow. That having been said, if you'd like to open a PR, we'd be happy to review it. Just be warned that there's a good chance it won't be merged for a little while.

**Comment by DVGY** [comment]
https://github.com/nextauthjs/next-auth/issues/6649 I saw there is new upcoming feature for Guest users. I think this will solve the issue ?

**Comment by arcticfly** [comment]
Unfortunately, I don’t believe guest features are very useful for most of what the project will be used for. We associate all experiments, datasets and fine-tuned models with projects, and we associate projects with authenticated users.

In theory we could add a concept of “public” projects, but I suspect that would be a larger undertaking than just adding email authentication. Additionally, I have a hard time imagining a good use-case for a public project, as most of the data users send OpenPipe is internal and probably sensitive.

Definitely open to feedback if you or anyone else thinks a public project would come in handy!

**Comment by DVGY** [comment]
Yaa I agree, @arcticfly.

**Comment by corbt** [comment]
Note: we’ve temporarily stopped development on the open-source version of the OpenPipe repository to integrate some proprietary third-party code. We hope to make the non-proprietary parts of the repository open again under an “open core” model once we get the bandwidth to do so. In the meantime, we are marking this repository as “archived” to let contributors know that it is no longer being maintained. Anyone is still free to fork and continue development off the existing open-source code, of course!
