### ISSUE TITLE
Adding a new tag in an update request log request silently fails if column doesn't already exist   

### ISSUE THREAD

**Issue by piersonmarks** [OpenPipe/openpipe#570]
**Situation:** 
I want to use the OpenPipe client to add a new log tag but I noticed if that if the tag column doesn't already exist, the updateLogTag request silently fails. The response object says one request was matched (like it was successfully updated), but the tag wasn't actually added. 

In order to make it work, you need to ensure the tag column exists by adding it to a request from the OpenAI OpenPipe client. Once the column exists, then you can just use the updateLogTags normally. 

I think the fix should be to check if the tag doesn't exist when calling updateLogTags, then it creates the column and updates the tag.

**Comment by arcticfly** [comment]
Hey @piersonmarks, thanks for opening the issue. I'll look into this and get back to you soon.

**Comment by arcticfly** [comment]
Ah, found the bug. It's related to a recent change we made to help request logs load faster. A PR for the fix is in.

The good news is, the tags that you added actually _are_ applied, you just might not be able see them yet. Updating a tag after this PR is merged (or recording a logged call with the tags you'd like to see, as you've discovered) will make the tags you've already added visible and searchable.

**Comment by piersonmarks** [comment]
Awesome - cool!

**Comment by arcticfly** [comment]
@piersonmarks The fix is deployed. Let us know if you run into any other bugs, and thanks again!
